name: Deploy Theme to WP Engine

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: pactlatrobedev
          SRC_PATH: "wp-content/themes/latrobeweb/"
          REMOTE_PATH: "wp-content/themes/latrobeweb/"
          PHP_LINT: false
          CACHE_CLEAR: true 